fix: Raising `ValueError` when using ips within pool library